# Site settings
title: Laura Artiles
email: lauraartiles@utexas.edu
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: laura_artiles_
github_username:  lauraartiles
markdown: kramdown
higlighter: true
